#define LIBUI_SERVER_VERSION "0.1.0-a"
#define LIBUI_SERVER_VERSION_MAJOR 0
#define LIBUI_SERVER_VERSION_MINOR 1
#define LIBUI_SERVER_VERSION_ALTER 0
#define LIBUI_SERVER_STATIC_BUILD 1
#define LIBUI_SERVER_HAS_OPENMP 1
