#define PANDAGL_VERSION "0.1.0-a"
#define PANDAGL_VERSION_MAJOR 0
#define PANDAGL_VERSION_MINOR 1
#define PANDAGL_VERSION_ALTER 0
#define PANDAGL_STATIC_BUILD 1
#define PANDAGL_HAS_TEXT 1
#define PANDAGL_HAS_FONT 1
#define PANDAGL_HAS_FREETYPE 1
/* #undef PANDAGL_HAS_FONTCONFIG */
#define PANDAGL_HAS_IMAGE 1
#define PANDAGL_HAS_LIBPNG 1
#define PANDAGL_HAS_LIBJPEG 1
