#define LIBUI_XML_VERSION "0.1.0-a"
#define LIBUI_XML_VERSION_MAJOR 0
#define LIBUI_XML_VERSION_MINOR 1
#define LIBUI_XML_VERSION_ALTER 0
#define LIBUI_XML_STATIC_BUILD 1
#define LIBUI_XML_HAS_LIBXML2 1
